ALTER TABLE patients
    ADD COLUMN alternate_phone VARCHAR(20),
    ADD COLUMN national_id VARCHAR(50),
    ADD COLUMN marital_status VARCHAR(20),
    ADD COLUMN profile_photo_url VARCHAR(500),
    ADD COLUMN address_line2 VARCHAR(200),
    ADD COLUMN city VARCHAR(100),
    ADD COLUMN postal_code VARCHAR(20),
    ADD COLUMN emergency_contact_name VARCHAR(100),
    ADD COLUMN emergency_contact_number VARCHAR(20),
    ADD COLUMN emergency_contact_relationship VARCHAR(50),
    ADD COLUMN blood_group VARCHAR(5),
    ADD COLUMN allergies TEXT,
    ADD COLUMN current_medications TEXT,
    ADD COLUMN has_diabetes BOOLEAN DEFAULT FALSE,
    ADD COLUMN has_hypertension BOOLEAN DEFAULT FALSE,
    ADD COLUMN has_heart_disease BOOLEAN DEFAULT FALSE,
    ADD COLUMN has_asthma BOOLEAN DEFAULT FALSE,
    ADD COLUMN has_epilepsy BOOLEAN DEFAULT FALSE,
    ADD COLUMN has_bleeding_disorders BOOLEAN DEFAULT FALSE,
    ADD COLUMN pregnancy_status VARCHAR(20),
    ADD COLUMN smoking_status VARCHAR(20),
    ADD COLUMN alcohol_consumption VARCHAR(20),
    ADD COLUMN chief_complaint TEXT,
    ADD COLUMN previous_dental_treatments TEXT,
    ADD COLUMN last_dental_visit_date DATE,
    ADD COLUMN referred_by VARCHAR(100),
    ADD COLUMN preferred_dentist VARCHAR(100),
    ADD COLUMN insurance_provider VARCHAR(100),
    ADD COLUMN insurance_policy_number VARCHAR(50),
    ADD COLUMN insurance_coverage_details TEXT,
    ADD COLUMN insurance_expiry_date DATE,
    ADD COLUMN registration_date DATE DEFAULT CURRENT_DATE,
    ADD COLUMN status VARCHAR(20) DEFAULT 'ACTIVE',
    ADD COLUMN consent_accepted BOOLEAN DEFAULT FALSE;

ALTER TABLE patients ALTER COLUMN gender TYPE VARCHAR(20);
