export interface PatientRequest {
  firstName: string
  lastName: string
  address: string
  contactNumber: string
  email: string
  dateOfBirth: string
  gender: 'MALE' | 'FEMALE' | 'OTHER'
  medicalNotes?: string
  alternatePhone: string
  nationalId: string
  maritalStatus: string
  profilePhotoUrl: string
  addressLine2: string
  city: string
  postalCode: string
  emergencyContactName: string
  emergencyContactNumber: string
  emergencyContactRelationship: string
  bloodGroup: string
  allergies: string
  currentMedications: string
  hasDiabetes: boolean
  hasHypertension: boolean
  hasHeartDisease: boolean
  hasAsthma: boolean
  hasEpilepsy: boolean
  hasBleedingDisorders: boolean
  pregnancyStatus: string
  smokingStatus: string
  alcoholConsumption: string
  chiefComplaint: string
  previousDentalTreatments: string
  lastDentalVisitDate: string
  referredBy: string
  preferredDentist: string
  insuranceProvider: string
  insurancePolicyNumber: string
  insuranceCoverageDetails: string
  insuranceExpiryDate: string
  registrationDate: string
  status: string
  consentAccepted: boolean
}

export interface PatientResponse {
  id: number
  patientNumber: string
  firstName: string
  lastName: string
  address: string
  contactNumber: string
  email: string
  dateOfBirth: string
  gender: string
  medicalNotes: string
  alternatePhone: string
  nationalId: string
  maritalStatus: string
  profilePhotoUrl: string
  addressLine2: string
  city: string
  postalCode: string
  emergencyContactName: string
  emergencyContactNumber: string
  emergencyContactRelationship: string
  bloodGroup: string
  allergies: string
  currentMedications: string
  hasDiabetes: boolean
  hasHypertension: boolean
  hasHeartDisease: boolean
  hasAsthma: boolean
  hasEpilepsy: boolean
  hasBleedingDisorders: boolean
  pregnancyStatus: string
  smokingStatus: string
  alcoholConsumption: string
  chiefComplaint: string
  previousDentalTreatments: string
  lastDentalVisitDate: string
  referredBy: string
  preferredDentist: string
  insuranceProvider: string
  insurancePolicyNumber: string
  insuranceCoverageDetails: string
  insuranceExpiryDate: string
  registrationDate: string
  status: string
  consentAccepted: boolean
  createdAt: string
  updatedAt: string
}
